AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 120
